# Export: playwright

"""
Generated by Selector CLI - Playwright (Python)
"""
from playwright.sync_api import sync_playwright


def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        page.goto('https://www.verdent.ai/signup?source=dashboard')

        # Element locators
        input_email = page.locator('input[type="email"]')
        input_text = page.locator('input[type="text"]')
        input_password = page.locator('input[type="password"]')
        button_button = page.locator('button[type="button"]')
        button_button = page.locator('button[type="button"]')
        a_5 = page.locator('a')
        a_6 = page.locator('a')
        a_7 = page.locator('a')

        # TODO: Add your automation logic here
        # Example:
        # input_email.fill('your text')

        # Keep browser open for inspection
        input('Press Enter to close browser...')

        browser.close()


if __name__ == '__main__':
    main()
