"""
Playwright code generator for Python
"""
from typing import List, Optional, Dict
from src.core.element import Element
from src.generators.base import CodeGenerator


class PlaywrightGenerator(CodeGenerator):
    """Generate Playwright (Python) code"""

    def get_format_name(self) -> str:
        return "playwright"

    def get_file_extension(self) -> str:
        return ".py"

    def generate(self, elements: List[Element], url: Optional[str] = None) -> str:
        """Generate Playwright Python code"""
        if not elements:
            return "# No elements to export"

        self.url = url or "https://example.com"

        # Group elements by selector to avoid duplicates
        selector_map: Dict[str, List[Element]] = {}
        for elem in elements:
            selector = self.format_selector(elem)
            if selector not in selector_map:
                selector_map[selector] = []
            selector_map[selector].append(elem)

        lines = []

        # Header
        lines.append('"""')
        lines.append("Generated by Selector CLI - Playwright (Python)")
        lines.append('"""')
        lines.append("from playwright.sync_api import sync_playwright")
        lines.append("")
        lines.append("")
        lines.append("def main():")
        lines.append("    with sync_playwright() as p:")
        lines.append("        browser = p.chromium.launch(headless=False)")
        lines.append("        page = browser.new_page()")
        lines.append(f"        page.goto('{self.url}')")
        lines.append("")

        # Element locators (deduplicated)
        lines.append("        # Locate elements")
        for selector, elems in selector_map.items():
            elem = elems[0]  # Use first element for variable naming
            var_name = self.generate_variable_name(elem)

            if len(elems) > 1:
                # Multiple elements with same selector - use locator.all()
                lines.append(f"        {var_name}_all = page.locator('{selector}').all()")
            else:
                # Single element
                lines.append(f"        {var_name} = page.locator('{selector}')")

        lines.append("")

        # Generate actionable example code
        lines.append("        # Example interactions")
        self._generate_action_examples(lines, selector_map)

        lines.append("")
        lines.append("        # Keep browser open for inspection")
        lines.append("        input('Press Enter to close browser...')")
        lines.append("")
        lines.append("        browser.close()")
        lines.append("")
        lines.append("")
        lines.append("if __name__ == '__main__':")
        lines.append("    main()")

        return "\n".join(lines)

    def _generate_action_examples(self, lines: List[str], selector_map: Dict[str, List[Element]]):
        """Generate realistic action examples based on element types"""
        input_count = 0
        button_count = 0

        for selector, elems in selector_map.items():
            elem = elems[0]
            var_name = self.generate_variable_name(elem)
            is_multiple = len(elems) > 1

            if elem.tag == "input":
                input_count += 1
                if input_count <= 3:  # Only show first 3 inputs
                    if is_multiple:
                        lines.append(f"        # {var_name}_all[0].fill('text')  # Fill first {elem.tag}")
                    else:
                        if elem.type == "email":
                            lines.append(f"        {var_name}.fill('user@example.com')")
                        elif elem.type == "password":
                            lines.append(f"        {var_name}.fill('your_password')")
                        elif elem.type in ("text", "search"):
                            placeholder = elem.placeholder or "text"
                            lines.append(f"        {var_name}.fill('{placeholder}')")
                        else:
                            lines.append(f"        # {var_name}.fill('text')")

            elif elem.tag == "button":
                button_count += 1
                if button_count == 1:  # Show first button
                    if is_multiple:
                        lines.append(f"        # {var_name}_all[0].click()  # Click first button")
                    else:
                        if elem.type == "submit" or "submit" in elem.text.lower():
                            lines.append(f"        {var_name}.click()  # Submit form")
                        else:
                            lines.append(f"        # {var_name}.click()")

            elif elem.tag == "select":
                if is_multiple:
                    lines.append(f"        # {var_name}_all[0].select_option('value')  # Select option")
                else:
                    lines.append(f"        # {var_name}.select_option('value')")

            elif elem.tag == "a":
                # Skip showing too many links
                pass

