"""
Puppeteer code generator for JavaScript/Node.js
"""
from typing import List, Optional
from src.core.element import Element
from src.generators.base import CodeGenerator


class PuppeteerGenerator(CodeGenerator):
    """Generate Puppeteer (JavaScript) code"""

    def get_format_name(self) -> str:
        return "puppeteer"

    def get_file_extension(self) -> str:
        return ".js"

    def generate(self, elements: List[Element], url: Optional[str] = None) -> str:
        """Generate Puppeteer JavaScript code"""
        if not elements:
            return "// No elements to export"

        self.url = url or "https://example.com"

        lines = []

        # Header
        lines.append("/**")
        lines.append(" * Generated by Selector CLI - Puppeteer (JavaScript)")
        lines.append(" */")
        lines.append("const puppeteer = require('puppeteer');")
        lines.append("")
        lines.append("(async () => {")
        lines.append("  const browser = await puppeteer.launch({ headless: false });")
        lines.append("  const page = await browser.newPage();")
        lines.append(f"  await page.goto('{self.url}');")
        lines.append("")

        # Element locators
        lines.append("  // Element locators")
        for elem in elements:
            var_name = self.generate_variable_name(elem)
            selector = self.format_selector(elem)
            lines.append(f"  const {var_name} = await page.$$('{selector}');")

        lines.append("")
        lines.append("  // TODO: Add your automation logic here")
        lines.append("  // Example:")
        if elements:
            first_elem = elements[0]
            var_name = self.generate_variable_name(first_elem)
            if first_elem.tag == "input":
                lines.append(f"  // await {var_name}[0].type('your text');")
            elif first_elem.tag == "button":
                lines.append(f"  // await {var_name}[0].click();")
            else:
                lines.append(f"  // await {var_name}[0].click();")

        lines.append("")
        lines.append("  // Keep browser open for inspection")
        lines.append("  console.log('Press Ctrl+C to close browser...');")
        lines.append("  await new Promise(resolve => setTimeout(resolve, 60000));")
        lines.append("")
        lines.append("  await browser.close();")
        lines.append("})();")

        return "\n".join(lines)
