"""
Selenium code generator for Python
"""
from typing import List, Optional
from src.core.element import Element
from src.generators.base import CodeGenerator


class SeleniumGenerator(CodeGenerator):
    """Generate Selenium (Python) code"""

    def get_format_name(self) -> str:
        return "selenium"

    def get_file_extension(self) -> str:
        return ".py"

    def generate(self, elements: List[Element], url: Optional[str] = None) -> str:
        """Generate Selenium Python code"""
        if not elements:
            return "# No elements to export"

        self.url = url or "https://example.com"

        lines = []

        # Header
        lines.append("\"\"\"")
        lines.append("Generated by Selector CLI - Selenium (Python)")
        lines.append("\"\"\"")
        lines.append("from selenium import webdriver")
        lines.append("from selenium.webdriver.common.by import By")
        lines.append("from selenium.webdriver.support.ui import WebDriverWait")
        lines.append("from selenium.webdriver.support import expected_conditions as EC")
        lines.append("")
        lines.append("")
        lines.append("def main():")
        lines.append("    driver = webdriver.Chrome()")
        lines.append(f"    driver.get('{self.url}')")
        lines.append("")

        # Element locators
        lines.append("    # Element locators")
        for elem in elements:
            var_name = self.generate_variable_name(elem)
            selector = self.format_selector(elem)
            lines.append(f"    {var_name} = driver.find_element(By.CSS_SELECTOR, '{selector}')")

        lines.append("")
        lines.append("    # TODO: Add your automation logic here")
        lines.append("    # Example:")
        if elements:
            first_elem = elements[0]
            var_name = self.generate_variable_name(first_elem)
            if first_elem.tag == "input":
                lines.append(f"    # {var_name}.send_keys('your text')")
            elif first_elem.tag == "button":
                lines.append(f"    # {var_name}.click()")
            else:
                lines.append(f"    # {var_name}.click()")

        lines.append("")
        lines.append("    # Keep browser open for inspection")
        lines.append("    input('Press Enter to close browser...')")
        lines.append("")
        lines.append("    driver.quit()")
        lines.append("")
        lines.append("")
        lines.append("if __name__ == '__main__':")
        lines.append("    main()")

        return "\n".join(lines)
