"""
Selenium code generator for Python
"""
from typing import List, Optional, Dict
from src.core.element import Element
from src.generators.base import CodeGenerator


class SeleniumGenerator(CodeGenerator):
    """Generate Selenium (Python) code"""

    def get_format_name(self) -> str:
        return "selenium"

    def get_file_extension(self) -> str:
        return ".py"

    def generate(self, elements: List[Element], url: Optional[str] = None) -> str:
        """Generate Selenium Python code"""
        if not elements:
            return "# No elements to export"

        self.url = url or "https://example.com"

        # Group elements by selector to avoid duplicates
        selector_map: Dict[str, List[Element]] = {}
        for elem in elements:
            selector = self.format_selector(elem)
            if selector not in selector_map:
                selector_map[selector] = []
            selector_map[selector].append(elem)

        lines = []

        # Header
        lines.append('"""')
        lines.append("Generated by Selector CLI - Selenium (Python)")
        lines.append('"""')
        lines.append("from selenium import webdriver")
        lines.append("from selenium.webdriver.common.by import By")
        lines.append("from selenium.webdriver.support.ui import WebDriverWait")
        lines.append("from selenium.webdriver.support import expected_conditions as EC")
        lines.append("")
        lines.append("")
        lines.append("def main():")
        lines.append("    driver = webdriver.Chrome()")
        lines.append(f"    driver.get('{self.url}')")
        lines.append("")

        # Element locators (deduplicated)
        lines.append("    # Locate elements")
        for selector, elems in selector_map.items():
            elem = elems[0]
            var_name = self.generate_variable_name(elem)

            if len(elems) > 1:
                lines.append(f"    {var_name}_all = driver.find_elements(By.CSS_SELECTOR, '{selector}')")
            else:
                lines.append(f"    {var_name} = driver.find_element(By.CSS_SELECTOR, '{selector}')")

        lines.append("")

        # Generate actionable example code
        lines.append("    # Example interactions")
        self._generate_action_examples(lines, selector_map)

        lines.append("")
        lines.append("    # Keep browser open for inspection")
        lines.append("    input('Press Enter to close browser...')")
        lines.append("")
        lines.append("    driver.quit()")
        lines.append("")
        lines.append("")
        lines.append("if __name__ == '__main__':")
        lines.append("    main()")

        return "\n".join(lines)

    def _generate_action_examples(self, lines: List[str], selector_map: Dict[str, List[Element]]):
        """Generate realistic action examples"""
        input_count = 0
        button_count = 0

        for selector, elems in selector_map.items():
            elem = elems[0]
            var_name = self.generate_variable_name(elem)
            is_multiple = len(elems) > 1

            if elem.tag == "input":
                input_count += 1
                if input_count <= 3:
                    if is_multiple:
                        lines.append(f"    # {var_name}_all[0].send_keys('text')")
                    else:
                        if elem.type == "email":
                            lines.append(f"    {var_name}.send_keys('user@example.com')")
                        elif elem.type == "password":
                            lines.append(f"    {var_name}.send_keys('your_password')")
                        elif elem.type in ("text", "search"):
                            placeholder = elem.placeholder or "text"
                            lines.append(f"    {var_name}.send_keys('{placeholder}')")
                        else:
                            lines.append(f"    # {var_name}.send_keys('text')")

            elif elem.tag == "button":
                button_count += 1
                if button_count == 1:
                    if is_multiple:
                        lines.append(f"    # {var_name}_all[0].click()")
                    else:
                        if elem.type == "submit" or "submit" in elem.text.lower():
                            lines.append(f"    {var_name}.click()  # Submit form")
                        else:
                            lines.append(f"    # {var_name}.click()")

            elif elem.tag == "select":
                if not is_multiple:
                    lines.append(f"    # from selenium.webdriver.support.select import Select")
                    lines.append(f"    # Select({var_name}).select_by_value('value')")

